package app.soine.analytics

import kotlin.random.Random

/**
 * Anonymous install identity for analytics.
 *
 * The identifier is a 128-bit cryptographically random value encoded
 * as 32 hex characters. It is generated lazily, persisted by the
 * caller (typically [AnalyticsPreferencesStore.write]) and never
 * derived from hardware identifiers, account IDs, or device serial
 * numbers.
 *
 * Re-generating the identifier is treated as a privacy-respecting
 * reset: callers MAY do it when the user deletes local data
 * (see [docs/privacy.md]). They MUST NOT do it on every app launch.
 */
object AnalyticsIdentity {

    /**
     * Returns the existing install id from [current] if present and
     * well-formed, otherwise generates and returns a new one. The
     * caller is responsible for persisting the returned value.
     */
    fun ensureInstallId(current: String?): String {
        if (current != null && isWellFormed(current)) return current
        return generate()
    }

    /**
     * Generates a fresh anonymous install id. Exposed for tests and
     * for explicit reset flows.
     */
    fun generate(): String {
        val bytes = ByteArray(16)
        Random.Default.nextBytes(bytes)
        return bytes.joinToString(separator = "") { byte ->
            byte.toUByte().toString(radix = 16).padStart(2, '0')
        }
    }

    /**
     * Returns true iff [candidate] matches the 32-hex-character shape
     * of an install id generated by this object.
     */
    fun isWellFormed(candidate: String): Boolean =
        candidate.length == 32 && candidate.all { it.isDigit() || it in 'a'..'f' }
}